#!/bin/bash

# Log file path
LOGFILE="/root/ansible-vm-init.log"

log(){
  message=$1
  echo "$(date): $message" >> $LOGFILE
}

start(){
  # Initialize VM with ansible
  log "Initializing VM with ansible"
  ansible-playbook -i "localhost," -c local /var/www/okeanos-LoD/webapp/ansible/playbooks/configure.yml >> $LOGFILE 2>&1
  retVal=$?
  if [ $retVal -eq 0 ]
  then
    log "Ansible VM initialization successful"
    rm /etc/init.d/ansible-vm-init
    update-rc.d ansible-vm-init remove
  else
    log "Ansible VM initialization failed with return value $retVal"
  fi

  return 0
}

case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 start"
esac
